version: '3'

services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - type: bind
        source: src
        target: /src
    depends_on:
      - db
    restart: always

  db:
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    image: postgres
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    restart: always

volumes:
  pgdata: